hexadecimal_1 = input('enter the first hexadecimal number:')
hexadecimal_2 = input('enter the second hexadecimal number:')
result = int(hexadecimal_1, 16) - int(hexadecimal_2, 16)
result = hex(result)
print(result)
